# Generated by Django 3.2.10 on 2024-03-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user_profile',
            new_name='user',
        ),
    ]
