# Generated by Django 3.2.10 on 2024-01-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_auto_20240121_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='symbol',
            new_name='name',
        ),
    ]
