# Generated by Django 3.2.10 on 2024-03-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_rename_user_profile_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbalance',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
