# Generated by Django 3.2.10 on 2024-05-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_alter_stockbalance_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='movement_percent',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
