# Generated by Django 3.2.10 on 2024-05-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_stock_movement_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.CharField(default='default_category', max_length=50),
        ),
    ]
