# Generated by Django 3.2.10 on 2024-01-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountportfolio',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=10000.0, max_digits=10),
        ),
    ]
