# Generated by Django 3.2.10 on 2024-01-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccountportfolio_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountportfolio',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=50000.0, max_digits=10),
        ),
    ]
